### ISSUE TITLE
Update README to correspond to official documentation

### ISSUE THREAD

**Issue by athieriot** [athieriot/docker-elastic-metricbeat#5]
https://www.elastic.co/guide/en/beats/metricbeat/5.x/_running_metricbeat_in_a_container.html

**Comment by monicasarbu** [comment]
The link has changed to https://www.elastic.co/guide/en/beats/metricbeat/5.x/running-in-container.html

**Comment by athieriot** [comment]
Thank you !

**Comment by athieriot** [comment]
Image and Readme updated with more details in ```5.2.0```

Another Docker Compose file is provided as well
