### ISSUE TITLE
Problem with bind mounting special filesystems

### ISSUE THREAD

**Issue by mimmus** [athieriot/docker-elastic-metricbeat#7]
According to Elastic official documentation, I need to bind mount /proc:

sudo docker run \
  --volume=/proc:/hostfs/proc:ro \ 
  --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \ 
  --volume=/:/hostfs:ro \ 
  --net=host 
  my/metricbeat:latest -system.hostfs=/hostfs

but it gives me an error:
oci runtime error: exec: "-system.hostfs=/hostfs": stat -system.hostfs=/hostfs: no such file or directory.

Any help?

**Comment by athieriot** [comment]
Hi there !

Thank you for reporting the issue.

This indeed won't work with the current image. Arguments won't be passed on the startup scripts.

I'll try to push a new version today that's going to allow you to use ```-system.hostfs=/hostfs``` as shown.

**Comment by mimmus** [comment]
Wonderful. I'm waiting...

**Comment by athieriot** [comment]
All right. The latest version is currently building (I also upgraded to the latest metricbeat version)

I've added more details on the README: https://hub.docker.com/r/athieriot/metricbeat/

But now it should work as required (By passing arguments):

```
docker run -d \
     -v=/proc:/hostfs/proc:ro \
     -v=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \
     -volume=/:/hostfs:ro \
     -v /home/username/metricbeat.yml:/metricbeat/metricbeat.yml \
     athieriot/metricbeat -system.hostfs=/hostfs
```

Please keep me up to date :)
